### ISSUE TITLE
Error downloading album if album name contains :

### ISSUE THREAD

**Issue by pdurandi** [Lordmau5/node-spotify-downloader#10]
If the album name contains **:** , it tries to create the directory but it hangs (in Windows).
Example album: https://play.spotify.com/album/2Q5Mrul369ojL9N8DWkWQZ

Original downloader.js
`_this.config.directory = _this.config.directory + "/" + _this.data.name.replace(/\//g, "-") + (" [" + album.date.year + "]") + "/";`

I have modified downloader.js with the same replace as Track.prototype.fixFilename and it works:
`_this.config.directory = _this.config.directory + "/" + _this.data.name.replace(/[\/\\?%*:|"<>]/g, "") + (" [" + album.date.year + "]") + "/";`

I believe it also happens when downloading a playlist with a ':' in this line:
`_this.config.directory = _this.config.directory + "/" + _this.data.name.replace(/\//g, "-") + "/"`

**Comment by Lordmau5** [comment]
Fixed
