### ISSUE TITLE
Excludes songs with the same name as "Already downloaded"

### ISSUE THREAD

**Issue by pranaymk** [Lordmau5/node-spotify-downloader#13]
When downloading a playlist with covers of the same song, and therefore the same track name, or totally different songs with the same name, it returns as having been already downloaded.

**Comment by kimgkimg** [comment]
I think this is related to the issue that I just logged.  The artist is no longer logged as part of the filename for the track, so covers of the same song would be detected as the same file even though they're by different artists.

**Comment by kelvinss** [comment]
This has already been solved on pull request #12. Just take a look at [this fork](https://github.com/kelvinss/node-spotify-downloader).  :)

**Comment by kimgkimg** [comment]
Kelvin,Thank you!
-geoff
