### ISSUE TITLE
Won´t work - module "coffee-script" missing…

### ISSUE THREAD

**Issue by GithubRW** [Lordmau5/node-spotify-downloader#2]
For what it looks this would be a **fantastic** CLI tool, but it won´t work for me.
Installed NodeJS Downloads v.6.0.0-x86 first, then unpacked the node-spotify-downloader-master.zip into the nodejs folder. "main.js" seems to be in place, but it always turns out to be the [module "coffee-script" missing](http://i.imgur.com/sr7fa1d.png)…
What am I doing wrong?
RW

**Comment by rafaeldamasceno** [comment]
@GithubRW Some modules this uses don't currently support 6.0.0. Use LTS 4.4.3 and run `npm install` at the tool directory for the first time to install the module dependencies. It should work after.

**Comment by swablueme** [comment]
I had the same problem as you and upon building I had a whole lot of issues such as 'error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found.' After a lot of head scratching and googling I ran 
`npm install --msvs_version=2013`
just then and it seemed to fix the npm install error and then trying to run the tool worked perfectly

**Comment by GithubRW** [comment]
@rafaeldamasceno: Wow, that´s exactly the solution. Worked smoothly after that.
_Thanks a million dude, you rule!_
@swablueme: Didn´t try it yet, but this command will make the 6.6.0 version work? Cool…

**Comment by GithubRW** [comment]
Many thanks for your help guys!
Can´t say how much I appreciate it.
