### ISSUE TITLE
Add {track.number} / {track.index}

### ISSUE THREAD

**Issue by okelet** [Lordmau5/node-spotify-downloader#25]
Add ``{track.number}`` to the tokens available for the ``-f`` parameter, in case of albums or tracks.

Add ``{track.index}`` to the tokens available for the ``-f`` parameter, in case of playlists, meaning the index of the song in the playlist, not the song number in the album it belongs to.

**Comment by jonaaa20** [comment]
{track.number} already works.

**Comment by kelvinss** [comment]
Yes, `{track.number}` already works, and I added it to README on #20. I'll work on the index token.

**Comment by Lordmau5** [comment]
Added
