### ISSUE TITLE
File/Folder Dialog for Path

### ISSUE THREAD

**Issue by sascha1337** [Lordmau5/node-spotify-downloader#26]
what about browse file dialog for setting the path in the webinterface to download and give the input field the default value that is used ?

;-) good job btw

**Comment by kelvinss** [comment]
It seems it's not actually possible to do browse dialog for folders with HTML/JS, just for files. :P

**Comment by kelvinss** [comment]
I just added the default value to the directory field on #28

**Comment by sascha1337** [comment]
this is awesome hehe

**Comment by Lordmau5** [comment]
Added
