### ISSUE TITLE
Error when getting "Rate limited"

### ISSUE THREAD

**Issue by rafaeldamasceno** [Lordmau5/node-spotify-downloader#30]
As of 4d21505ccacfbf067f446e23189e80d3ec42fcee, whenever the program gets "Rate limited", an unexpected error occurs and cause the program to freeze:

>    - Error received: TrackError: Rate limited
>    - TrackError: Rate limited ... { Retrying in 10 seconds }
>    - Error received: TypeError: Cannot read property 'path' of undefined

I suggest reverting these changes while we look for a better way to do this, as per #29.

**Comment by rafaeldamasceno** [comment]
@Lordmau5 Please close the issue! I think everything is working well now.

**Comment by kelvinss** [comment]
I think who creates the issue can close it. Down there ↓ should be a "close issue" button.

**Comment by kelvinss** [comment]
Btw, could you test the my last update on the ["new-instance" branch](https://github.com/kelvinss/node-spotify-downloader/commits/fix-new-instance)?

**Comment by rafaeldamasceno** [comment]
@kelvinss Right, there is. Oops.
