### ISSUE TITLE
Collaborating artists not listed in ID3 tags

### ISSUE THREAD

**Issue by ethus3h** [Lordmau5/node-spotify-downloader#36]
E.g. when downloading True Colors (by Kesha and Zedd), it only lists Zedd in the artist tag, and only True Colors in the title tag....

**Comment by kelvinss** [comment]
I thick I'll add an "artists" placeholder path format, which would return the artist separated by a `,`.

How should multiple artists be handled in ID3 tags? Just using separating them the same way by a delimiter?

**Comment by ethus3h** [comment]
I think another downloader solved this problem by listing them with " / " between each one
