### ISSUE TITLE
Hangs on Track Download

### ISSUE THREAD

**Issue by gpresland** [Lordmau5/node-spotify-downloader#51]
Using 
`node main.js -u <username> -p <password> -i https://play.spotify.com/track/2I0Q1wxFRdnDYtG6Q8W47S` hangs with the following error.

```
node-spotify-downloader\node_modules\spotify-web\lib\util.js:26
  for(var str=[],i=0,len=hex.length;len-1>i;i+=2) {
```

**Comment by akselm** [comment]
I had that problem with nodejs v6.2.1, then downgraded to v4.4.5 LTS release, and now it works fine.

**Comment by gpresland** [comment]
Nice. Works.
Just download the .exe from `https://nodejs.org/en/download/` and put it in the folder.
