### ISSUE TITLE
Not downloading. Error in node_modules\sp otify-web\lib\util.js:26

### ISSUE THREAD

**Issue by lattenlui** [Lordmau5/node-spotify-downloader#9]
Hi,

I get this message when downloading songs:

 - Login successful!
 - Handling playlist ...
 - Playlist: Schlager
 - Processing 1253 tracks
 - Downloading: Matthias Reim - Alles was ich will

T:\node-spotify-downloader-master\node-spotify-downloader-master\node_modules\sp
otify-web\lib\util.js:26
  for(var str=[],i=0,len=hex.length;len-1>i;i+=2) {

All I can see is that the app stores a 0kb file in my directory. Tried the server and cli version on Windows 8.1 and both on Linux Mint. Same messages and always just 0kb file. Tried different playlist also.
Please help me fix this issue ;-)

**Comment by alfrfrey** [comment]
I had this issue too (OSX), I removed my node install and reinstalling it did the trick - i'm currently using v6.0.0, however i've seen people having success with the current LTS too.

**Comment by lattenlui** [comment]
Thank you!
removed 6.1 installation and installed LTS. Now works like charm, ;-)
